importy, připojení datasetu
kontrola
srovnání jmen a příjmení
duplicity (vyřešit účast ve dvou cyklech, přenos striků)
vyřazení starých
vyřazení šmejdů + print
napárování
oba směry párů
print

# Instalace

In [30]:
!pip install --upgrade gspread oauth2client
!pip install --upgrade gspread pandas

Requirement already satisfied: gspread in /usr/local/lib/python3.11/dist-packages (6.2.0)
Requirement already satisfied: oauth2client in /usr/local/lib/python3.11/dist-packages (4.1.3)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from gspread) (2.38.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from gspread) (1.2.1)
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from oauth2client) (0.22.0)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.11/dist-packages (from oauth2client) (0.6.1)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.11/dist-packages (from oauth2client) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from oauth2client) (4.9)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.11/dist-packages (from oauth2client) (1.17.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread) (5.5.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2>=0.9.1->oauth2client) (3.2.3)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2025.1.31)
Requirement already satisfied: gspread in /usr/local/lib/python3.11/dist-packages (6.2.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.3)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from gspread) (2.38.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from gspread) (1.2.1)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2025.1.31)

# Importy

In [31]:
import pandas as pd
import gspread
from google.auth import default
from google.colab import auth
from gspread_dataframe import set_with_dataframe

# Připojení google sheets

In [32]:
# Autorizace a připojení ke Google Sheets pomocí vestavěného Google Colab přihlašování
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# Použití ID vašeho Google Sheetu
spreadsheet_id = '1f_owr5KPUi2lgrjdvq-4YFW2_JPVaxt4VYk93CLamYQ'
spreadsheet = gc.open_by_key(spreadsheet_id)

# Vyberte list/tabulku podle názvu nebo indexu
worksheet = spreadsheet.get_worksheet(0)  # První list (index 0)

# Načtení datasetu

In [33]:
# Načtení všech dat z listu do DataFrame pomocí gspread
data = worksheet.get_all_records()

# Převedení dat na Pandas DataFrame
df = pd.DataFrame(data)

In [34]:
# 1) Načtení df, oprava datumů
df['Datum'] = pd.to_datetime(df['Časová značka'], dayfirst=True)

# Definice jmen a vytvoření listů

In [35]:
# Definice seznamu mužských jmen
muzi = [
    "Abadon", "Abdon", "Ábel", "Abelard", "Abraham", "Abrahám", "Absolón", "Adalbert", "Adam",
    "Adin", "Adolf", "Adrián", "Agaton", "Achil", "Alan", "Alban", "Albert", "Albín", "Albrecht",
    "Aldo", "Aleš", "Alexandr", "Alexej", "Alfons", "Alfréd", "Alois", "Alva", "Alvar", "Alvin",
    "Amadeus", "Amand", "Amát", "Ambrož", "Ámos", "Anastáz", "Anatol", "Anděl", "Andrej", "Anselm",
    "Antal", "Antonín", "Aram", "Ariel", "Aristid", "Arkád", "Armand", "Armin", "Arne", "Arnold",
    "Arnošt", "Árón", "Arpád", "Artur", "Artuš", "Arzen", "Atanas", "Atila", "August", "Aurel",
    "Axel", "Baltazar", "Barnabáš", "Bartoloměj", "Bazil", "Beatus", "Bedřich", "Benedikt",
    "Benjamín", "Bernard", "Bertold", "Bertram", "Bivoj", "Blahomil", "Blahomír", "Blahoslav",
    "Blažej", "Bohdan", "Bohuchval", "Bohumil", "Bohumír", "Bohuslav", "Bohuš", "Bojan", "Bolemír",
    "Boleslav", "Bonifác", "Boris", "Bořek", "Bořislav", "Bořivoj", "Božetěch", "Božidar",
    "Božislav", "Branimír", "Branislav", "Bratislav", "Brian", "Brit", "Bruno", "Břetislav",
    "Budimír", "Budislav", "Budivoj", "Cecil", "Celestýn", "Cézar", "Ctibor", "Ctirad", "Ctislav",
    "Cyprián", "Cyril", "Čeněk", "Čestmír", "Čistoslav", "Dag", "Dalibor", "Dalimil", "Dalimír",
    "Damián", "Dan", "Daniel", "Darek", "Darius", "David", "Denis", "Děpold", "Dětmar", "Dětřich",
    "Dezider", "Dimitrij", "Dino", "Diviš", "Dluhoš", "Dobromil", "Dobromír", "Dobroslav",
    "Dominik", "Donald", "Donát", "Dorián", "Drahomil", "Drahomír", "Drahoslav", "Drahoš",
    "Drahotín", "Dušan", "Edgar", "Edmond", "Edvard", "Edvín", "Egmont", "Egon", "Eliáš",
    "Elizej", "Elmar", "Elvis", "Emanuel", "Emerich", "Emil", "Engelbert", "Erazim", "Erhard",
    "Erik", "Ernest", "Ervín", "Eusebius", "Evald", "Evan", "Evarist", "Evžen", "Ezechiel",
    "Ezra", "Fabián", "Faust", "Fedor", "Felix", "Ferdinand", "Fidel", "Filemon", "Filibert",
    "Filip", "Filomen", "Flavián", "Florentýn", "Florián", "Fortunát", "František", "Fridolín",
    "Gabin", "Gabriel", "Gál", "Garik", "Gaston", "Gedeon", "Genadij", "Gerald", "Gerard",
    "Gerazim", "Géza", "Gilbert", "Gleb", "Glen", "Gorazd", "Gordon", "Gothard", "Gracián",
    "Grant", "Gunter", "Gustav", "Hanuš", "Harald", "Haštal", "Havel", "Helmut", "Herbert",
    "Heřman", "Hilar", "Hjalmar", "Homér", "Honor", "Horác", "Horst", "Horymír", "Hostimil",
    "Hostislav", "Hostivít", "Hovard", "Hubert", "Hugo", "Hvězdoslav", "Hyacint", "Hynek",
    "Hypolit", "Chrabroš", "Chranibor", "Chranislav", "Chrudoš", "Chval", "Ignác", "Igor",
    "Ilja", "Inocenc", "Irenej", "Irvin", "Ivan", "Ivar", "Ivo", "Izaiáš", "Izák", "Izidor",
    "Izmael", "Jacek", "Jáchym", "Jakub", "Jan", "Jarmil", "Jarolím", "Jaromír", "Jaroslav",
    "Jasoň", "Jeremiáš", "Jeroným", "Jiljí", "Jimram", "Jindřich", "Jiří", "Job", "Joel",
    "Jonáš", "Jonatan", "Jordan", "Josef", "Jošt", "Jozue", "Juda", "Julián", "Julius", "Justýn",
    "Kajetán", "Kamil", "Karel", "Kasián", "Kastor", "Kašpar", "Kazimír", "Kilián", "Kim",
    "Klement", "Knut", "Koloman", "Kolombín", "Konrád", "Konstantýn", "Kornel", "Kosma",
    "Krasomil", "Krasoslav", "Kristián", "Kryšpín", "Kryštof", "Křesomysl", "Kurt", "Květoslav",
    "Květoš", "Kvido", "Ladislav", "Lambert", "Lars", "Laurenc", "Lazar", "Leandr", "Leo",
    "Leodegar", "Leonard", "Leonid", "Leontýn", "Leopold", "Leoš", "Lešek", "Lev", "Libor",
    "Liboslav", "Lionel", "Livius", "Lotar", "Lubomír", "Lubor", "Luboš", "Lucián", "Luděk",
    "Ludivoj", "Ludomír", "Ludoslav", "Ludvík", "Lukáš", "Lukrecius", "Lumír", "Lutobor",
    "Magnus", "Makar", "Manfréd", "Mansvet", "Manuel", "Marcel", "Marek", "Marián", "Marin",
    "Mario", "Martin", "Matěj", "Matouš", "Max", "Maxmilián", "Mečislav", "Medard", "Melichar",
    "Merlin", "Mervin", "Metod", "Michal", "Mikoláš", "Milan", "Milíč", "Milivoj", "Miloň",
    "Milorad", "Miloslav", "Miloš", "Milota", "Milouš", "Milovan", "Mirek", "Miromil", "Miron",
    "Miroslav", "Mlad", "Mnata", "Mnislav", "Modest", "Mojmír", "Mojžíš", "Morgan", "Moric",
    "Mstislav", "Myrtil", "Napoleon", "Narcis", "Natan", "Natanael", "Něhoslav", "Neklan",
    "Nepomuk", "Nezamysl", "Nikita", "Nikodém", "Nikola", "Norbert", "Norman", "Odolen",
    "Odon", "Oktavián", "Olaf", "Olbram", "Oldřich", "Oleg", "Oliver", "Omar", "Ondřej",
    "Orest", "Oskar", "Osvald", "Ota", "Otakar", "Otmar", "Ovidius", "Palmiro", "Pankrác",
    "Pantaleon", "Paris", "Parsival", "Paskal", "Patrik", "Pavel", "Pelhřim", "Perikles",
    "Petr", "Petronius", "Pius", "Platón", "Polykarp", "Pravdomil", "Prokop", "Prosper",
    "Přemysl", "Přibyslav", "Radek", "Radhost", "Radim", "Radivoj", "Radmil", "Radomír",
    "Radoslav", "Radovan", "Radúz", "Rafael", "Raimund", "Rainald", "Rainer", "Rainhard",
    "Rajko", "Ralf", "Ramon", "Randolf", "Ranek", "Ratibor", "Ratmír", "Redmond", "Remig",
    "Remus", "Renát", "René", "Richard", "Robert", "Robin", "Robinson", "Rodan", "Roderik",
    "Roger", "Roch", "Roland", "Rolf", "Roman", "Romeo", "Romuald", "Romul", "Ronald",
    "Rostislav", "Ruben", "Rudolf", "Rufus", "Rupert", "Ruslan", "Řehoř", "Sámo", "Samson",
    "Samuel", "Saturnin", "Saul", "Sáva", "Sebastián", "Sedrik", "Serafín", "Serenus",
    "Sergej", "Servác", "Severín", "Sidon", "Sigfríd", "Silván", "Silvestr", "Simeon",
    "Sinkler", "Sixt", "Slávek", "Slaviboj", "Slavoj", "Slavomil", "Slavomír", "Smil",
    "Soběslav", "Sokrat", "Soter", "Spytihněv", "Stanimír", "Stanislav", "Stojan",
    "Stojmír", "Svatobor", "Svatomír", "Svatopluk", "Svatoslav", "Sven", "Svetozar",
    "Šalomoun", "Šavel", "Šimon", "Šťasta", "Štěpán", "Tadeáš", "Tankred", "Taras",
    "Teobald", "Teodor", "Teodorik", "Teodoz", "Teofan", "Teofil", "Terenc", "Tiber",
    "Tibor", "Tichomil", "Tichomír", "Tichon", "Timon", "Timotej", "Timur", "Titus",
    "Tobiáš", "Tomáš", "Tomislav", "Torkvát", "Torsten", "Tristan", "Udo", "Ulrich",
    "Upton", "Urban", "Uve", "Václav", "Vadim", "Valdemar", "Valentýn", "Valerián",
    "Valtr", "Vasil", "Vavřinec", "Veleslav", "Velimír", "Věnceslav", "Vendelín",
    "Verner", "Věroslav", "Vidor", "Viktor", "Vilém", "Vilibald", "Vilmar", "Vincenc",
    "Virgil", "Virgin", "Vít", "Vítězslav", "Vitold", "Vivian", "Vladan", "Vladimír",
    "Vladislav", "Vladivoj", "Vlastimil", "Vlastimír", "Vlastislav", "Vlk", "Vojen",
    "Vojmil", "Vojmír", "Vojslav", "Vojtěch", "Volfgang", "Vratislav", "Vsevolod",
    "Všebor", "Všerad", "Všeslav", "Záboj", "Zachar", "Záviš", "Zbyhněv", "Zbyněk",
    "Zbyslav", "Zdeněk", "Zderad", "Zdislav", "Zeno", "Zikmund", "Zlatan", "Zlatomír",
    "Zoltán", "Zoran", "Zoroslav", "Zosim", "Zvonimír", "Žarko", "Ždan", "Želibor",
    "Želimír", "Želislav", "Žitomír", "Žitoslav", "Živan"
]

In [36]:
# Definice seznamu ženských jmen
zeny = [
    "Abigail", "Ada", "Adalberta", "Adéla", "Adelaida", "Adina", "Adolfa", "Adriana", "Afra", "Agáta",
    "Aglaja", "Aida", "Alana", "Albena", "Alberta", "Albína", "Alena", "Aleška", "Alexandra", "Alfréda",
    "Alice", "Alida", "Alina", "Alma", "Aloisie", "Alžběta", "Amálie", "Amanda", "Amáta", "Anabela",
    "Anastázie", "Anatázie", "Anatólie", "Anděla", "Andrea", "Aneta", "Anežka", "Angelika", "Anita",
    "Anna", "Anselma", "Antonie", "Apolena", "Arabela", "Aranka", "Areta", "Ariana", "Ariela", "Arleta",
    "Armida", "Arna", "Arnolda", "Arnoštka", "Astrid", "Atanázie", "Augusta", "Aurélie", "Aurora",
    "Babeta", "Barbora", "Beáta", "Beatrice", "Bedřiška", "Bela", "Běla", "Belinda", "Benedikta",
    "Berenika", "Bernarda", "Berta", "Bertolda", "Bianka", "Bibiana", "Birgit", "Blahomila", "Blahomíra",
    "Blahoslava", "Blanka", "Blažena", "Bohdana", "Bohumila", "Bohumíra", "Bohuna", "Bohuslava",
    "Bojana", "Bojislava", "Boleslava", "Bořislava", "Božena", "Božetěcha", "Božidara", "Branimíra",
    "Bratislava", "Brenda", "Brigita", "Brita", "Bronislava", "Bruna", "Brunhilda", "Břetislava",
    "Cecílie", "Celestýna", "Celie", "Celina", "Ctibora", "Ctirada", "Ctislava", "Cyntie", "Cyrila",
    "Čeňka", "Čestmíra", "Čistoslava", "Dagmar", "Dalibora", "Dalida", "Dalie", "Dalila", "Dalimila",
    "Dalimíra", "Damaris", "Damiána", "Dana", "Danica", "Daniela", "Danuta", "Darie", "Darina",
    "Davida", "Debora", "Delie", "Denisa", "Diana", "Dina", "Dita", "Diviška", "Dobrava", "Dobromila",
    "Dobromíra", "Dobroslava", "Dominika", "Donalda", "Donáta", "Dora", "Doris", "Doubravka", "Drahomila",
    "Drahomíra", "Drahoslava", "Drahuše", "Dulcinea", "Dušana", "Edita", "Eduarda", "Egona", "Ela",
    "Elektra", "Eleonora", "Elfrída", "Eliška", "Elvíra", "Elza", "Ema", "Emanuela", "Emílie", "Erika",
    "Erna", "Ervína", "Ester", "Etela", "Eufrozína", "Eulálie", "Eunika", "Eusebie", "Eva", "Evelína",
    "Evženie", "Fabie", "Fatima", "Faustýna", "Féba", "Fedora", "Felicita", "Ferdinanda", "Fidelie",
    "Filipa", "Filoména", "Flavie", "Flóra", "Florentýna", "Františka", "Frída", "Gabriela", "Gaja",
    "Galina", "Garika", "Gema", "Geralda", "Gerarda", "Gerda", "Gertruda", "Gilberta", "Gina", "Gita",
    "Gizela", "Glorie", "Gordana", "Grácie", "Gražina", "Gréta", "Grizelda", "Gudrun", "Gustava",
    "Gvendolína", "Halina", "Hana", "Háta", "Havla", "Heda", "Hedvika", "Heidrun", "Helena", "Helga",
    "Herberta", "Hermína", "Herta", "Hilda", "Hortenzie", "Horymíra", "Hostimila", "Hostislava",
    "Hvězdoslava", "Hyacinta", "Chranislava", "Iboja", "Ida", "Ignácie", "Ildika", "Iljana", "Ilona",
    "Ilza", "Inéz", "Ingeborg", "Ingrid", "Inka", "Irena", "Iris", "Irma", "Iva", "Ivana", "Iveta",
    "Ivona", "Izabela", "Izidora", "Izolda", "Jadrana", "Jakubka", "Jana", "Jarmila", "Jarolíma",
    "Jaromíra", "Jaroslava", "Jasmína", "Jasna", "Jelena", "Jenovéfa", "Jesika", "Jindra", "Jindřiška",
    "Jiřina", "Jitka", "Jolana", "Jolanta", "Jordana", "Jorga", "Josefa", "Jovana", "Judita", "Juliána",
    "Julie", "Justýna", "Juta", "Kamila", "Karin", "Karla", "Karmela", "Karmen", "Karolína", "Kateřina",
    "Katrin", "Kazi", "Kazimíra", "Kira", "Klára", "Klaudie", "Klementýna", "Kleopatra", "Klotylda",
    "Koleta", "Kolombína", "Konstance", "Konzuel", "Kora", "Kordula", "Kornélie", "Krasava", "Krasomila",
    "Kristýna", "Kunhuta", "Květa", "Květoslava", "Lada", "Ladislava", "Larisa", "Laura", "Laurencie",
    "Lea", "Léda", "Lejla", "Lenka", "Leokádie", "Leona", "Leontýna", "Leopolda", "Leticie", "Liběna",
    "Libora", "Liboslava", "Libuše", "Liliana", "Lina", "Linda", "Livie", "Ljuba", "Lola", "Loreta",
    "Lorna", "Lota", "Lubomíra", "Lucie", "Ludiše", "Luďka", "Ludmila", "Ludomíra", "Ludoslava",
    "Ludvíka", "Lujza", "Lukrécie", "Lumíra", "Lýdie", "Mabel", "Magda", "Magdaléna", "Mahulena",
    "Mája", "Malvína", "Manon", "Manuela", "Marcela", "Margit", "Mariana", "Marie", "Marieta",
    "Marika", "Marilyn", "Marina", "Mariola", "Marion", "Marisa", "Marita", "Markéta", "Marlena",
    "Marta", "Martina", "Matylda", "Maud", "Maxima", "Mečislava", "Médea", "Melánie", "Melinda",
    "Melisa", "Mercedes", "Michaela", "Milada", "Milana", "Milena", "Miloslava", "Milred", "Miluše",
    "Mína", "Mirabela", "Miranda", "Mirela", "Miriam", "Mirka", "Miromila", "Miroslava", "Mnislava",
    "Mona", "Monika", "Muriel", "Myrna", "Naďa", "Naděžda", "Naneta", "Narcisa", "Natálie", "Nataša",
    "Neda", "Nela", "Nevena", "Nika", "Nikodéma", "Nikol", "Nila", "Nina", "Noema", "Nona", "Nora",
    "Norberta", "Norma", "Odeta", "Ofélie", "Oktávie", "Oldřiška", "Olga", "Olivie", "Olympie",
    "Ondřejka", "Otakara", "Otýlie", "Oxana", "Palmira", "Pamela", "Paskala", "Patricie", "Pavla",
    "Pelagie", "Penelopa", "Perla", "Perzida", "Petra", "Petronela", "Petula", "Pilar", "Polyxena",
    "Pravomila", "Pravoslav", "Pravoslava", "Priska", "Prokopa", "Přibyslava", "Radana", "Radka",
    "Radmila", "Radomíra", "Radoslava", "Rafaela", "Ráchel", "Rajsa", "Ramona", "Rebeka", "Regína",
    "Renáta", "René", "Ria", "Richarda", "Rina", "Rita", "Roberta", "Robina", "Romana", "Rostislava",
    "Rovena", "Roxana", "Róza", "Rozálie", "Rozalinda", "Rozamunda", "Rozana", "Rozina", "Rozita",
    "Rozvita", "Rudolfa", "Rut", "Rút", "Růžena", "Řehořka", "Sabina", "Sabrina", "Salomea", "Samuela",
    "Sandra", "Sára", "Saskie", "Saxona", "Selena", "Selma", "Senta", "Serafína", "Serena", "Scholastika",
    "Sibyla", "Sidonie", "Silvána", "Silvie", "Simona", "Skarlet", "Slavěna", "Slávka", "Slavomila",
    "Slavomíra", "Soběslava", "Sofronie", "Solveig", "Soňa", "Sotira", "Stanislava", "Stáza", "Stela",
    "Svatava", "Svatoslava", "Světla", "Sylva", "Šárka", "Šarlota", "Šimona", "Štěpánka", "Tamara",
    "Táňa", "Taťána", "Tea", "Tekla", "Teodora", "Teodozie", "Teofila", "Tereza", "Tomáška", "Toska",
    "Ulrika", "Una", "Uršula", "Václava", "Valburga", "Valdemara", "Valentýna", "Valérie", "Vanda",
    "Vanesa", "Věduna", "Veleslava", "Věnceslava", "Vendelína", "Vendula", "Venuše", "Věra", "Veronika",
    "Věroslava", "Vesna", "Viktorie", "Vilma", "Vincencie", "Viola", "Virgínie", "Víta", "Vítězslava",
    "Viviana", "Vladana", "Vladimíra", "Vladislava", "Vlasta", "Vlastimila", "Vlastimíra", "Vlastislava",
    "Vojmíra", "Vojslava", "Vojtěška", "Voršila", "Vratislava", "Xaverie", "Xenie", "Zaida", "Zaira",
    "Zbyhněva", "Zbyslava", "Zdeňka", "Zdislava", "Zenobie", "Zina", "Zita", "Zlata", "Zlatomíra",
    "Zoe", "Zora", "Zoroslava", "Zuzana", "Zvonimíra", "Žakelína", "Žaneta", "Ždana", "Želimíra",
    "Želislava", "Žitomíra", "Živa", "Žofie"
]

In [37]:
seznam_jmen = muzi + zeny

# Eliminace debilů: swap jmen a příjmení

In [38]:
# Funkce pro kontrolu a prohození křestního jména a příjmení
def kontrola_a_prohozeni(row):
    prijmeni = row['Příjmení']
    krestni_jmeno = row['Křestní jméno']

    # Případ, kdy křestní jméno je ve sloupci "Příjmení" a naopak
    if prijmeni in seznam_jmen and krestni_jmeno not in seznam_jmen:
        return pd.Series([krestni_jmeno, prijmeni], index=['Příjmení', 'Křestní jméno'])
    elif krestni_jmeno in seznam_jmen and prijmeni not in seznam_jmen:
        return pd.Series([prijmeni, krestni_jmeno], index=['Příjmení', 'Křestní jméno'])
    else:
        return pd.Series([prijmeni, krestni_jmeno], index=['Příjmení', 'Křestní jméno'])

In [39]:
# Aplikace funkce na celý DataFrame
df[['Příjmení', 'Křestní jméno']] = df.apply(kontrola_a_prohozeni, axis=1)

# Oprava datumů

In [40]:
# 1) Oprava datumů - Převod sloupce 'Časová značka' na datetime
df['Datum'] = pd.to_datetime(df['Časová značka'], dayfirst=True)

# Eliminace debilů: Přenesení striků

In [41]:
# 2) Funkce pro doplnění strike1 a strike2 na základě existující hodnoty v rámci uživatele (e-mail)
def doplnit_striky(df):
    df['strike1'] = df.groupby('e-mail')['strike1'].transform(lambda x: x.max())
    df['strike2'] = df.groupby('e-mail')['strike2'].transform(lambda x: x.max())
    return df

In [42]:
# Aplikujeme funkci pro doplnění strike1 a strike2
df = doplnit_striky(df)

In [43]:
# 3) Převod sloupců strike1 a strike2 na bool
df['strike1'] = df['strike1'].apply(lambda x: True if str(x).lower() == 'true' else False)
df['strike2'] = df['strike2'].apply(lambda x: True if str(x).lower() == 'true' else False)

# Filtrace starých dat

In [44]:
# 4) Funkce pro filtrování a odstranění záznamů starších než zadané datum
def drop_stare_zaznamy(df):
    # Zeptáme se uživatele na datum ve formátu dd-mm-yyyy
    zadane_datum = input("Zadejte datum ve formátu DD-MM-YYYY: ")

    # Převod zadaného data na formát datetime
    try:
        zadane_datum = pd.to_datetime(zadane_datum, format="%d-%m-%Y")
    except ValueError:
        print("Zadané datum není platné. Prosím, použijte formát DD-MM-YYYY.")
        return df

    # Odstraníme všechny záznamy starší než zadané datum
    df_filtered = df[df['Datum'] >= zadane_datum]

    return df_filtered

In [60]:
# 5) Dropnutí všech starších záznamů než input a zobrazení těch, co zůstaly
df_filtered = drop_stare_zaznamy(df)

Zadejte datum ve formátu DD-MM-YYYY: 01-09-2024

In [61]:
# Výpis výsledku po filtrování
print("Záznamy po filtrování:")
display(df_filtered)

Záznamy po filtrování:

,Časová značka,Příjmení,Křestní jméno,e-mail,strike1,strike2,Datum
7,18.12.2024 12:23:46,Marková,Zuzana,Zuzikmarkova@seznam.cz,False,False,2024-12-18 12:23:46
8,18.12.2024 12:27:02,Nistorová,Adéla,adela@sebestovi.eu,False,False,2024-12-18 12:27:02
9,18.12.2024 12:39:43,Ryrychová,Tereza,tereza.ryrychova@seznam.cz,False,False,2024-12-18 12:39:43
10,18.12.2024 12:42:57,Talášeková,Nataša,n.talasekova@seznam.cz,False,False,2024-12-18 12:42:57
11,18.12.2024 12:45:56,Harvalíková,Jarka,bejruska@seznam.cz,False,False,2024-12-18 12:45:56
12,18.12.2024 12:51:43,Zemanová,Eva,evaevazemanova@seznam.cz,False,False,2024-12-18 12:51:43
13,18.12.2024 13:04:27,Gromanová,Barbora,barunkagromanova@seznam.cz,False,False,2024-12-18 13:04:27
14,18.12.2024 13:09:35,Zajacová,Pavla,pavlazajacova113@seznam.cz,False,False,2024-12-18 13:09:35
15,18.12.2024 13:16:06,Kvízová,Eliška,elikviz@seznam.cz,False,False,2024-12-18 13:16:06
16,18.12.2024 13:21:56,Jirásková,Veronika,verca.manurova@seznam.cz,False,False,2024-12-18 13:21:56
17,18.12.2024 13:32:55,Musilová,Hana,hana.m.musilova@gmail.com,False,False,2024-12-18 13:32:55
18,18.12.2024 13:44:00,Doomed,Dave,kytkal@email.cz,False,False,2024-12-18 13:44:00
19,18.12.2024 13:48:32,Petrželková,Irena,ruby.wild.boar@gmail.com,False,False,2024-12-18 13:48:32
20,18.12.2024 14:04:57,Kozel,Jakub,kozelkubik@seznam.cz,False,False,2024-12-18 14:04:57
21,18.12.2024 14:20:56,Arltová,Martina,Martina.arltova@gmail.com,False,False,2024-12-18 14:20:56
22,18.12.2024 14:47:24,Vitoušková,Anna,anna.vitouskova@seznam.cz,False,False,2024-12-18 14:47:24
23,18.12.2024 15:01:25,Kladivová,Pavla,Kladivovapa@seznam.cz,False,False,2024-12-18 15:01:25
24,18.12.2024 15:02:26,Látalová,Tereza,ztracena.selka@gmail.com,False,False,2024-12-18 15:02:26
25,18.12.2024 16:22:57,Škardová,Kristýna,kristy.skardova@email.cz,False,False,2024-12-18 16:22:57
26,18.12.2024 16:23:12,Řezníčková,Lucie,luckareznickova@gmail.com,False,False,2024-12-18 16:23:12
27,18.12.2024 18:29:43,Drábková,Lenka,drabkova34@seznam.cz,False,False,2024-12-18 18:29:43
28,18.12.2024 19:18:47,Polívková,Kateřina,wolfka44@gmail.com,False,False,2024-12-18 19:18:47
29,18.12.2024 19:48:02,Marková,Tereza,Tereza7772@seznam.cz,False,False,2024-12-18 19:48:02
30,18.12.2024 19:50:29,Bednářová,Kristýna,safiestea@gmail.com,False,False,2024-12-18 19:50:29
31,18.12.2024 22:10:32,Březina,Jiří,brezinajiri998@gmail.com,False,False,2024-12-18 22:10:32
32,18.12.2024 22:19:18,Havlová,Linda,havlova.linda@seznam.cz,False,False,2024-12-18 22:19:18
33,18.12.2024 22:19:36,Paterová,Radka,pater.radka@seznam.cz,False,False,2024-12-18 22:19:36
34,18.12.2024 22:23:57,Uhlíková,Tery,tery.uhlikova@gmail.com,False,False,2024-12-18 22:23:57
35,18.12.2024 23:13:39,Blažková,Hana,hanule.blazkova@gmail.com,False,False,2024-12-18 23:13:39
36,18.12.2024 23:27:20,Smoleň,Zita,zitniakovazita@gmail.com,False,False,2024-12-18 23:27:20
37,19.12.2024 0:47:42,Cinklová,Kateřina,katerina.cinklova@gmail.com,False,False,2024-12-19 00:47:42
38,19.12.2024 4:01:47,Janečková,Tereza,geminem@seznam.cz,False,False,2024-12-19 04:01:47
39,19.12.2024 8:04:58,Hustáková,Magdaléna,magda.hustakova@seznam.cz,False,False,2024-12-19 08:04:58
40,19.12.2024 9:43:05,Minsterová,Veronika,v.minsterova@gmail.com,False,False,2024-12-19 09:43:05
41,19.12.2024 18:11:20,Brusenbauch,Michaela,mishelinka@seznam.cz,False,False,2024-12-19 18:11:20
42,19.12.2024 19:01:05,Rábová,Veronika,Diablicos@centrum.cz,False,False,2024-12-19 19:01:05
43,19.12.2024 20:53:48,Englerová,Lada,Lada.musilova@seznam.cz,False,False,2024-12-19 20:53:48
44,20.12.2024 21:37:59,Černošková,Magdalena,magdalenka.cernoskova@gmail.com,False,False,2024-12-20 21:37:59
45,23.12.2024 19:38:13,Jarošová,Šárka,padoukova@gmail.com,False,False,2024-12-23 19:38:13
46,23.12.2024 19:46:10,Arnautova,Ester,arnautova.ester@gmail.com,False,False,2024-12-23 19:46:10
47,24.12.2024 13:38:29,Steklá,Veronika,vercik.st@seznam.cz,False,False,2024-12-24 13:38:29
48,24.12.2024 18:44:39,Prokopová,Renáta,prokopova.rena@gmail.com,False,False,2024-12-24 18:44:39
49,25.12.2024 13:33:28,Filip,Tomáš,filtocz@gmail.com,False,False,2024-12-25 13:33:28
50,26.12.2024 15:30:28,cejka,marian,marian.cejka@seznam.cz,False,False,2024-12-26 15:30:28
51,26.12.2024 23:48:55,Pospíšilová,Michaela,michaela.posp7@gmail.com,False,False,2024-12-26 23:48:55

# Drop dulicit a napárování dvojic se zohledněním udělených striků

In [62]:
# Funkce pro odstranění duplicit na základě e-mailu, ponechá nejnovější záznam
def remove_email_duplicates(df):
    # Ponecháme poslední záznam pro každý e-mail na základě sloupce Datum
    df = df.sort_values('Datum').drop_duplicates(subset='e-mail', keep='last')
    return df

# 6) Párování dvojic dle požadovaného klíče (po filtrování dat a odstranění duplicit)

# 1. Uživatelé bez strike
df_no_strikes = df_filtered[(df_filtered['strike1'] == False) & (df_filtered['strike2'] == False)]
df_no_strikes = remove_email_duplicates(df_no_strikes)  # Odstranění duplicit

# 2. Uživatelé s jedním strike
df_one_strike = df_filtered[((df_filtered['strike1'] == True) & (df_filtered['strike2'] == False)) | ((df_filtered['strike1'] == False) & (df_filtered['strike2'] == True))]
df_one_strike = remove_email_duplicates(df_one_strike)  # Odstranění duplicit

# 3. Uživatelé s dvěma striky
df_two_strikes = df_filtered[(df_filtered['strike1'] == True) & (df_filtered['strike2'] == True)]
df_two_strikes = remove_email_duplicates(df_two_strikes)  # Odstranění duplicit

# Výstup vyčištěných výsledků
display(df_no_strikes)
display(df_one_strike)
display(df_two_strikes)

,Časová značka,Příjmení,Křestní jméno,e-mail,strike1,strike2,Datum
7,18.12.2024 12:23:46,Marková,Zuzana,Zuzikmarkova@seznam.cz,False,False,2024-12-18 12:23:46
8,18.12.2024 12:27:02,Nistorová,Adéla,adela@sebestovi.eu,False,False,2024-12-18 12:27:02
9,18.12.2024 12:39:43,Ryrychová,Tereza,tereza.ryrychova@seznam.cz,False,False,2024-12-18 12:39:43
10,18.12.2024 12:42:57,Talášeková,Nataša,n.talasekova@seznam.cz,False,False,2024-12-18 12:42:57
11,18.12.2024 12:45:56,Harvalíková,Jarka,bejruska@seznam.cz,False,False,2024-12-18 12:45:56
12,18.12.2024 12:51:43,Zemanová,Eva,evaevazemanova@seznam.cz,False,False,2024-12-18 12:51:43
13,18.12.2024 13:04:27,Gromanová,Barbora,barunkagromanova@seznam.cz,False,False,2024-12-18 13:04:27
14,18.12.2024 13:09:35,Zajacová,Pavla,pavlazajacova113@seznam.cz,False,False,2024-12-18 13:09:35
15,18.12.2024 13:16:06,Kvízová,Eliška,elikviz@seznam.cz,False,False,2024-12-18 13:16:06
16,18.12.2024 13:21:56,Jirásková,Veronika,verca.manurova@seznam.cz,False,False,2024-12-18 13:21:56
17,18.12.2024 13:32:55,Musilová,Hana,hana.m.musilova@gmail.com,False,False,2024-12-18 13:32:55
18,18.12.2024 13:44:00,Doomed,Dave,kytkal@email.cz,False,False,2024-12-18 13:44:00
19,18.12.2024 13:48:32,Petrželková,Irena,ruby.wild.boar@gmail.com,False,False,2024-12-18 13:48:32
20,18.12.2024 14:04:57,Kozel,Jakub,kozelkubik@seznam.cz,False,False,2024-12-18 14:04:57
21,18.12.2024 14:20:56,Arltová,Martina,Martina.arltova@gmail.com,False,False,2024-12-18 14:20:56
22,18.12.2024 14:47:24,Vitoušková,Anna,anna.vitouskova@seznam.cz,False,False,2024-12-18 14:47:24
23,18.12.2024 15:01:25,Kladivová,Pavla,Kladivovapa@seznam.cz,False,False,2024-12-18 15:01:25
24,18.12.2024 15:02:26,Látalová,Tereza,ztracena.selka@gmail.com,False,False,2024-12-18 15:02:26
25,18.12.2024 16:22:57,Škardová,Kristýna,kristy.skardova@email.cz,False,False,2024-12-18 16:22:57
26,18.12.2024 16:23:12,Řezníčková,Lucie,luckareznickova@gmail.com,False,False,2024-12-18 16:23:12
27,18.12.2024 18:29:43,Drábková,Lenka,drabkova34@seznam.cz,False,False,2024-12-18 18:29:43
28,18.12.2024 19:18:47,Polívková,Kateřina,wolfka44@gmail.com,False,False,2024-12-18 19:18:47
29,18.12.2024 19:48:02,Marková,Tereza,Tereza7772@seznam.cz,False,False,2024-12-18 19:48:02
30,18.12.2024 19:50:29,Bednářová,Kristýna,safiestea@gmail.com,False,False,2024-12-18 19:50:29
31,18.12.2024 22:10:32,Březina,Jiří,brezinajiri998@gmail.com,False,False,2024-12-18 22:10:32
32,18.12.2024 22:19:18,Havlová,Linda,havlova.linda@seznam.cz,False,False,2024-12-18 22:19:18
33,18.12.2024 22:19:36,Paterová,Radka,pater.radka@seznam.cz,False,False,2024-12-18 22:19:36
34,18.12.2024 22:23:57,Uhlíková,Tery,tery.uhlikova@gmail.com,False,False,2024-12-18 22:23:57
35,18.12.2024 23:13:39,Blažková,Hana,hanule.blazkova@gmail.com,False,False,2024-12-18 23:13:39
36,18.12.2024 23:27:20,Smoleň,Zita,zitniakovazita@gmail.com,False,False,2024-12-18 23:27:20
37,19.12.2024 0:47:42,Cinklová,Kateřina,katerina.cinklova@gmail.com,False,False,2024-12-19 00:47:42
38,19.12.2024 4:01:47,Janečková,Tereza,geminem@seznam.cz,False,False,2024-12-19 04:01:47
39,19.12.2024 8:04:58,Hustáková,Magdaléna,magda.hustakova@seznam.cz,False,False,2024-12-19 08:04:58
40,19.12.2024 9:43:05,Minsterová,Veronika,v.minsterova@gmail.com,False,False,2024-12-19 09:43:05
41,19.12.2024 18:11:20,Brusenbauch,Michaela,mishelinka@seznam.cz,False,False,2024-12-19 18:11:20
42,19.12.2024 19:01:05,Rábová,Veronika,Diablicos@centrum.cz,False,False,2024-12-19 19:01:05
43,19.12.2024 20:53:48,Englerová,Lada,Lada.musilova@seznam.cz,False,False,2024-12-19 20:53:48
44,20.12.2024 21:37:59,Černošková,Magdalena,magdalenka.cernoskova@gmail.com,False,False,2024-12-20 21:37:59
45,23.12.2024 19:38:13,Jarošová,Šárka,padoukova@gmail.com,False,False,2024-12-23 19:38:13
46,23.12.2024 19:46:10,Arnautova,Ester,arnautova.ester@gmail.com,False,False,2024-12-23 19:46:10
47,24.12.2024 13:38:29,Steklá,Veronika,vercik.st@seznam.cz,False,False,2024-12-24 13:38:29
48,24.12.2024 18:44:39,Prokopová,Renáta,prokopova.rena@gmail.com,False,False,2024-12-24 18:44:39
49,25.12.2024 13:33:28,Filip,Tomáš,filtocz@gmail.com,False,False,2024-12-25 13:33:28
50,26.12.2024 15:30:28,cejka,marian,marian.cejka@seznam.cz,False,False,2024-12-26 15:30:28
51,26.12.2024 23:48:55,Pospíšilová,Michaela,michaela.posp7@gmail.com,False,False,2024-12-26 23:48:55

Empty DataFrame
Columns: [Časová značka, Příjmení, Křestní jméno, e-mail, strike1, strike2, Datum]
Index: []

Empty DataFrame
Columns: [Časová značka, Příjmení, Křestní jméno, e-mail, strike1, strike2, Datum]
Index: []

In [63]:
# Funkce pro vytvoření dvojic nebo trojic
def vytvorit_dvojice(data):
    result = []
    for i in range(0, len(data), 2):
        if i + 2 <= len(data):
            result.append(data[i:i+2])
        else:
            result.append(data[i:i+3])
    return result

In [64]:
# Seznamy uživatelů s jejich příjmeními, křestními jmény a daty registrace
list_no_strikes = df_no_strikes[['Příjmení', 'Křestní jméno', 'Datum']].values.tolist()
list_one_strike = df_one_strike[['Příjmení', 'Křestní jméno', 'Datum']].values.tolist()
list_two_strikes = df_two_strikes[['Příjmení', 'Křestní jméno', 'Datum']].values.tolist()

In [65]:
# Kontrola počtu uživatelů se dvěma striky
if len(list_two_strikes) == 1:
    list_one_strike.append(list_two_strikes[0])
    list_two_strikes = []

In [66]:
# Kontrola počtu uživatelů s jedním strikem
if len(list_one_strike) == 1:
    list_no_strikes.append(list_one_strike[0])
    list_one_strike = []

In [67]:
# Vytvoření dvojic/trojic pro každou kategorii
dvojice_no_strikes = vytvorit_dvojice(list_no_strikes)
dvojice_one_strike = vytvorit_dvojice(list_one_strike)
dvojice_two_strikes = vytvorit_dvojice(list_two_strikes)

In [68]:
# Funkce pro vytvoření tabulky
def vytvorit_tabulku(dvojice):
    rows = []
    for group in dvojice:
        if len(group) == 2:
            rows.append([group[0][0], group[0][1], group[0][2], group[1][0], group[1][1], group[1][2]])
        elif len(group) == 3:
            rows.append([group[0][0], group[0][1], group[0][2], group[1][0], group[1][1], group[1][2], group[2][0], group[2][1], group[2][2]])
    return rows

In [69]:
# Vytvoření tabulek pro každou kategorii
tabulka_no_strikes = vytvorit_tabulku(dvojice_no_strikes)
tabulka_one_strike = vytvorit_tabulku(dvojice_one_strike)
tabulka_two_strikes = vytvorit_tabulku(dvojice_two_strikes)

In [70]:
# Konverze na DataFrame a zobrazení tabulky (včetně sloupců s datem registrace)
df_no_strikes_tab = pd.DataFrame(tabulka_no_strikes, columns=['Příjmení 1', 'Křestní jméno 1', 'Datum 1', 'Příjmení 2', 'Křestní jméno 2', 'Datum 2'])
df_one_strike_tab = pd.DataFrame(tabulka_one_strike, columns=['Příjmení 1', 'Křestní jméno 1', 'Datum 1', 'Příjmení 2', 'Křestní jméno 2', 'Datum 2'])
df_two_strikes_tab = pd.DataFrame(tabulka_two_strikes, columns=['Příjmení 1', 'Křestní jméno 1', 'Datum 1', 'Příjmení 2', 'Křestní jméno 2', 'Datum 2'])

In [71]:
# Zobrazení tabulek
print("Tabulka uživatelů bez strike:")
display(df_no_strikes_tab)

print("\nTabulka uživatelů s jedním strike:")
display(df_one_strike_tab)

print("\nTabulka uživatelů s dvěma striky:")
display(df_two_strikes_tab)

Tabulka uživatelů bez strike:

,Příjmení 1,Křestní jméno 1,Datum 1,Příjmení 2,Křestní jméno 2,Datum 2
0,Marková,Zuzana,2024-12-18 12:23:46,Nistorová,Adéla,2024-12-18 12:27:02
1,Ryrychová,Tereza,2024-12-18 12:39:43,Talášeková,Nataša,2024-12-18 12:42:57
2,Harvalíková,Jarka,2024-12-18 12:45:56,Zemanová,Eva,2024-12-18 12:51:43
3,Gromanová,Barbora,2024-12-18 13:04:27,Zajacová,Pavla,2024-12-18 13:09:35
4,Kvízová,Eliška,2024-12-18 13:16:06,Jirásková,Veronika,2024-12-18 13:21:56
5,Musilová,Hana,2024-12-18 13:32:55,Doomed,Dave,2024-12-18 13:44:00
6,Petrželková,Irena,2024-12-18 13:48:32,Kozel,Jakub,2024-12-18 14:04:57
7,Arltová,Martina,2024-12-18 14:20:56,Vitoušková,Anna,2024-12-18 14:47:24
8,Kladivová,Pavla,2024-12-18 15:01:25,Látalová,Tereza,2024-12-18 15:02:26
9,Škardová,Kristýna,2024-12-18 16:22:57,Řezníčková,Lucie,2024-12-18 16:23:12
10,Drábková,Lenka,2024-12-18 18:29:43,Polívková,Kateřina,2024-12-18 19:18:47
11,Marková,Tereza,2024-12-18 19:48:02,Bednářová,Kristýna,2024-12-18 19:50:29
12,Březina,Jiří,2024-12-18 22:10:32,Havlová,Linda,2024-12-18 22:19:18
13,Paterová,Radka,2024-12-18 22:19:36,Uhlíková,Tery,2024-12-18 22:23:57
14,Blažková,Hana,2024-12-18 23:13:39,Smoleň,Zita,2024-12-18 23:27:20
15,Cinklová,Kateřina,2024-12-19 00:47:42,Janečková,Tereza,2024-12-19 04:01:47
16,Hustáková,Magdaléna,2024-12-19 08:04:58,Minsterová,Veronika,2024-12-19 09:43:05
17,Brusenbauch,Michaela,2024-12-19 18:11:20,Rábová,Veronika,2024-12-19 19:01:05
18,Englerová,Lada,2024-12-19 20:53:48,Černošková,Magdalena,2024-12-20 21:37:59
19,Jarošová,Šárka,2024-12-23 19:38:13,Arnautova,Ester,2024-12-23 19:46:10
20,Steklá,Veronika,2024-12-24 13:38:29,Prokopová,Renáta,2024-12-24 18:44:39
21,Filip,Tomáš,2024-12-25 13:33:28,cejka,marian,2024-12-26 15:30:28

Tabulka uživatelů s jedním strike:

Empty DataFrame
Columns: [Příjmení 1, Křestní jméno 1, Datum 1, Příjmení 2, Křestní jméno 2, Datum 2]
Index: []

Tabulka uživatelů s dvěma striky:

Empty DataFrame
Columns: [Příjmení 1, Křestní jméno 1, Datum 1, Příjmení 2, Křestní jméno 2, Datum 2]
Index: []

In [72]:
# Funkce pro anonymizaci e-mailu
def anonymizovat_email(email):
    try:
        local_part, domain = email.split('@')
    except ValueError:
        return email  # Pokud není validní e-mailová adresa, vracíme původní hodnotu
    if len(local_part) > 2:
        anonymized_local = local_part[0] + '*' * (len(local_part) - 2) + local_part[-1]
    else:
        anonymized_local = local_part  # Pokud je lokální díl krátký, neanonymizujeme
    return anonymized_local + '@' + domain

# Aplikace anonymizace e-mailů na celý DataFrame df_filtered
df_filtered['e-mail'] = df_filtered['e-mail'].apply(anonymizovat_email)

# Seznamy uživatelů s jejich příjmeními, křestními jmény a anonymizovanými e-maily
df_no_strikes['e-mail'] = df_no_strikes['e-mail'].apply(anonymizovat_email)
df_one_strike['e-mail'] = df_one_strike['e-mail'].apply(anonymizovat_email)
df_two_strikes['e-mail'] = df_two_strikes['e-mail'].apply(anonymizovat_email)

# Vytvoření seznamů s anonymizovanými e-maily
list_no_strikes = df_no_strikes[['Příjmení', 'Křestní jméno', 'e-mail']].values.tolist()
list_one_strike = df_one_strike[['Příjmení', 'Křestní jméno', 'e-mail']].values.tolist()
list_two_strikes = df_two_strikes[['Příjmení', 'Křestní jméno', 'e-mail']].values.tolist()

# Funkce pro vytvoření dvojic nebo trojic s kruhovým propojením
def vytvorit_dvojice(data):
    result = []
    for i in range(0, len(data), 2):
        if i + 2 < len(data):
            result.append(data[i:i+2])
        elif i + 2 == len(data):
            result.append(data[i:i+2])
        elif i + 1 == len(data):
            last_two = result[-1]
            result[-1] = [last_two[0], last_two[1], data[i]]  # vytvoření trojice
    return result

# Funkce pro vytvoření tabulky s kruhovými trojicemi
def vytvorit_dvojradkovou_tabulku(dvojice):
    rows = []
    for group in dvojice:
        if len(group) == 2:
            rows.append([group[0][0], group[0][1], group[0][2], group[1][0], group[1][1], group[1][2]])
            rows.append([group[1][0], group[1][1], group[1][2], group[0][0], group[0][1], group[0][2]])
        elif len(group) == 3:
            rows.append([group[0][0], group[0][1], group[0][2], group[1][0], group[1][1], group[1][2]])
            rows.append([group[1][0], group[1][1], group[1][2], group[2][0], group[2][1], group[2][2]])
            rows.append([group[2][0], group[2][1], group[2][2], group[0][0], group[0][1], group[0][2]])
    return rows

# Funkce pro kontrolu prázdných seznamů a vytvoření tabulek
def vytvorit_a_zobrazit_tabulku(dvojice, nadpis):
    if dvojice:
        tabulka_dup = vytvorit_dvojradkovou_tabulku(dvojice)
        df_dup = pd.DataFrame(tabulka_dup, columns=['Příjmení 1', 'Křestní jméno 1', 'E-mail 1', 'Příjmení 2', 'Křestní jméno 2', 'E-mail 2'])
        print(nadpis)
        print(df_dup.sort_values('Příjmení 1').to_string(index=False))  # Zajišťuje správné tisknutí místo display()
    else:
        print(f"Žádní uživatelé v kategorii: {nadpis}")

# Vytvoření dvojřádkových tabulek pro každou kategorii
vytvorit_a_zobrazit_tabulku(vytvorit_dvojice(list_no_strikes), "Tabulka uživatelů bez strike")
vytvorit_a_zobrazit_tabulku(vytvorit_dvojice(list_one_strike), "\nTabulka uživatelů s jedním strike")
vytvorit_a_zobrazit_tabulku(vytvorit_dvojice(list_two_strikes), "\nTabulka uživatelů se dvěma striky")

Tabulka uživatelů bez strike
  Příjmení 1 Křestní jméno 1                        E-mail 1   Příjmení 2 Křestní jméno 2                        E-mail 2
    Arltová          Martina       M*************a@gmail.com   Vitoušková            Anna       a*************a@seznam.cz
   Arnautova           Ester       a*************r@gmail.com     Jarošová           Šárka             p*******a@gmail.com
  Bednářová         Kristýna             s*******a@gmail.com     Marková          Tereza            T********2@seznam.cz
    Blažková            Hana       h*************a@gmail.com       Smoleň            Zita        z************a@gmail.com
Brusenbauch        Michaela             m********a@seznam.cz       Rábová        Veronika            D*******s@centrum.cz
     Březina           Jiří         b************8@gmail.com      Havlová           Linda         h***********a@seznam.cz
   Cinklová         Kateřina     k***************a@gmail.com   Janečková          Tereza                g*****m@seznam.cz
      Doomed            Dave                 k****l@email.cz    Musilová             Hana      h*************a@gmail.com
    Drábková           Lenka            d********4@seznam.cz   Polívková         Kateřina              w******4@gmail.com
  Englerová             Lada         L***********a@seznam.cz   Černošková       Magdalena m*******************a@gmail.com
       Filip           Tomáš               f*****z@gmail.com        cejka          marian          m**********a@seznam.cz
   Gromanová         Barbora      b**************a@seznam.cz     Zajacová           Pavla      p**************3@seznam.cz
 Harvalíková           Jarka              b******a@seznam.cz    Zemanová              Eva        e************a@seznam.cz
     Havlová           Linda         h***********a@seznam.cz      Březina           Jiří         b************8@gmail.com
   Hustáková       Magdaléna       m*************a@seznam.cz   Minsterová        Veronika          v**********a@gmail.com
  Janečková          Tereza                g*****m@seznam.cz    Cinklová         Kateřina     k***************a@gmail.com
    Jarošová           Šárka             p*******a@gmail.com    Arnautova           Ester       a*************r@gmail.com
   Jirásková        Veronika        v************a@seznam.cz      Kvízová          Eliška               e*****z@seznam.cz
  Kladivová           Pavla            K*********a@seznam.cz    Látalová          Tereza         z************a@gmail.com
       Kozel          Jakub             k********k@seznam.cz  Petrželková           Irena        r************r@gmail.com
     Kvízová          Eliška               e*****z@seznam.cz    Jirásková        Veronika        v************a@seznam.cz
   Látalová          Tereza         z************a@gmail.com   Kladivová           Pavla            K*********a@seznam.cz
    Marková          Zuzana           Z**********a@seznam.cz   Nistorová           Adéla               a***a@sebestovi.eu
    Marková          Tereza            T********2@seznam.cz    Bednářová         Kristýna             s*******a@gmail.com
  Minsterová        Veronika          v**********a@gmail.com    Hustáková       Magdaléna       m*************a@seznam.cz
   Musilová             Hana      h*************a@gmail.com        Doomed            Dave                 k****l@email.cz
  Nistorová           Adéla               a***a@sebestovi.eu     Marková          Zuzana           Z**********a@seznam.cz
   Paterová            Radka           p*********a@seznam.cz     Uhlíková            Tery         t***********a@gmail.com
 Petrželková           Irena        r************r@gmail.com        Kozel          Jakub             k********k@seznam.cz
  Polívková         Kateřina              w******4@gmail.com     Drábková           Lenka            d********4@seznam.cz
Pospíšilová        Michaela        m************7@gmail.com         Filip           Tomáš               f*****z@gmail.com
   Prokopová          Renáta        p************a@gmail.com       Steklá        Veronika             v*******t@seznam.cz
  Ryrychová          Tereza       t**************a@seznam.cz  Talášeková          Nataša           n**********a@seznam.cz
      Rábová        Veronika            D*******s@centrum.cz Brusenbauch        Michaela             m********a@seznam.cz
      Smoleň            Zita        z************a@gmail.com     Blažková            Hana       h*************a@gmail.com
      Steklá        Veronika             v*******t@seznam.cz    Prokopová          Renáta        p************a@gmail.com
 Talášeková          Nataša           n**********a@seznam.cz   Ryrychová          Tereza       t**************a@seznam.cz
    Uhlíková            Tery         t***********a@gmail.com    Paterová            Radka           p*********a@seznam.cz
  Vitoušková            Anna       a*************a@seznam.cz     Arltová          Martina       M*************a@gmail.com
    Zajacová           Pavla      p**************3@seznam.cz    Gromanová         Barbora      b**************a@seznam.cz
   Zemanová              Eva        e************a@seznam.cz  Harvalíková           Jarka              b******a@seznam.cz
       cejka          marian          m**********a@seznam.cz Pospíšilová        Michaela        m************7@gmail.com
  Černošková       Magdalena m*******************a@gmail.com   Englerová             Lada         L***********a@seznam.cz
 Řezníčková           Lucie        l*************a@gmail.com    Škardová        Kristýna        k*************a@email.cz
   Škardová        Kristýna        k*************a@email.cz   Řezníčková           Lucie        l*************a@gmail.com
Žádní uživatelé v kategorii:
Tabulka uživatelů s jedním strike
Žádní uživatelé v kategorii:
Tabulka uživatelů se dvěma striky

<ipython-input-72-6f10761012c2>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['e-mail'] = df_filtered['e-mail'].apply(anonymizovat_email)

# Export dat do spreadcheatu

In [73]:
# Autorizace a připojení ke Google Sheets pomocí vestavěného Google Colab přihlašování
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# Použití ID vašeho Google Sheetu
spreadsheet_id = '1f_owr5KPUi2lgrjdvq-4YFW2_JPVaxt4VYk93CLamYQ'
spreadsheet = gc.open_by_key(spreadsheet_id)

# Vyberte list/tabulku podle názvu nebo indexu (první list datasetu nesmí být smazán)
worksheet = spreadsheet.get_worksheet(0)

# Pokud neexistuje druhý list, vytvoříme ho, jinak vymažeme stará data
try:
    worksheet_results = spreadsheet.get_worksheet(1)
    worksheet_results.clear()  # Vymazání starých dat ze druhého listu
except:
    worksheet_results = spreadsheet.add_worksheet(title="Výsledky", rows="1000", cols="20")

# Funkce pro anonymizaci e-mailu
def anonymizovat_email(email):
    try:
        local_part, domain = email.split('@')
    except ValueError:
        return email  # Pokud není validní e-mailová adresa, vracíme původní hodnotu
    # Vytvoříme anonymizovaný lokální díl (první a poslední písmeno, mezi nimi hvězdičky)
    if len(local_part) > 2:
        anonymized_local = local_part[0] + '*' * (len(local_part) - 2) + local_part[-1]
    else:
        anonymized_local = local_part  # Pokud je lokální díl krátký, neanonymizujeme
    return anonymized_local + '@' + domain

# Aplikace anonymizace e-mailů na celý DataFrame df_filtered
df_filtered['e-mail'] = df_filtered['e-mail'].apply(anonymizovat_email)

# Seznamy uživatelů s jejich příjmeními, křestními jmény a anonymizovanými e-maily
df_no_strikes['e-mail'] = df_no_strikes['e-mail'].apply(anonymizovat_email)
df_one_strike['e-mail'] = df_one_strike['e-mail'].apply(anonymizovat_email)
df_two_strikes['e-mail'] = df_two_strikes['e-mail'].apply(anonymizovat_email)

# Vytvoření seznamů s anonymizovanými e-maily
list_no_strikes = df_no_strikes[['Příjmení', 'Křestní jméno', 'e-mail']].values.tolist()
list_one_strike = df_one_strike[['Příjmení', 'Křestní jméno', 'e-mail']].values.tolist()
list_two_strikes = df_two_strikes[['Příjmení', 'Křestní jméno', 'e-mail']].values.tolist()

# Funkce pro vytvoření dvojic nebo trojic
def vytvorit_dvojice(data):
    result = []
    for i in range(0, len(data), 2):
        if i + 2 <= len(data):
            result.append(data[i:i+2])
        else:
            result.append(data[i:i+3])
    return result

# Vytvoření dvojic/trojic pro každou kategorii
dvojice_no_strikes = vytvorit_dvojice(list_no_strikes)
dvojice_one_strike = vytvorit_dvojice(list_one_strike)
dvojice_two_strikes = vytvorit_dvojice(list_two_strikes)

# Funkce pro vytvoření tabulky s anonymizovanými e-maily
def vytvorit_dvojradkovou_tabulku(dvojice):
    rows = []
    for group in dvojice:
        if len(group) == 2:
            # Dvojice (dvě řádky, jednou obráceně)
            rows.append([group[0][0], group[0][1], group[0][2], group[1][0], group[1][1], group[1][2]])
            rows.append([group[1][0], group[1][1], group[1][2], group[0][0], group[0][1], group[0][2]])
        elif len(group) == 3:
            # Trojice (tři řádky s rotací)
            rows.append([group[0][0], group[0][1], group[0][2], group[1][0], group[1][1], group[1][2]])
            rows.append([group[1][0], group[1][1], group[1][2], group[2][0], group[2][1], group[2][2]])
            rows.append([group[2][0], group[2][1], group[2][2], group[0][0], group[0][1], group[0][2]])
    return rows

# Spojení tabulek ze všech kategorií
tabulka_no_strikes_dup = vytvorit_dvojradkovou_tabulku(dvojice_no_strikes)
tabulka_one_strike_dup = vytvorit_dvojradkovou_tabulku(dvojice_one_strike)
tabulka_two_strikes_dup = vytvorit_dvojradkovou_tabulku(dvojice_two_strikes)

# Kombinace všech výsledků do jedné tabulky
final_data = tabulka_no_strikes_dup + tabulka_one_strike_dup + tabulka_two_strikes_dup

# Vytvoření DataFrame z kombinovaných dat (správné sloupce s anonymizovanými e-maily)
df_final = pd.DataFrame(final_data, columns=['Příjmení 1', 'Křestní jméno 1', 'E-mail 1', 'Příjmení 2', 'Křestní jméno 2', 'E-mail 2'])

# Zapsání výsledné tabulky do druhého listu v Google Sheets
set_with_dataframe(worksheet_results, df_final)

print("Výsledná tabulka byla úspěšně uložena do druhého listu v Google Sheets.")

<ipython-input-73-30fa1472fedb>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['e-mail'] = df_filtered['e-mail'].apply(anonymizovat_email)

Výsledná tabulka byla úspěšně uložena do druhého listu v Google Sheets.